// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage(
    "Reliability",
    "CA2007:Consider calling ConfigureAwait on the awaited task",
    Justification = "Remove to simplify project."
)]
[assembly: SuppressMessage(
    "Style",
    "IDE0161:Convert to file-scoped namespace",
    Justification = "Autogenerated files",
    Scope = "namespaceanddescendants",
    Target = "~N:Alexandria.Persistence.Migrations"
)]
[assembly: SuppressMessage(
    "Style",
    "IDE0300:Simplify collection initialization",
    Justification = "Autogenerated files",
    Scope = "namespaceanddescendants",
    Target = "~N:Alexandria.Persistence.Migrations"
)]
[assembly: SuppressMessage(
    "Design",
    "CA1062:Validate arguments of public methods",
    Justification = "Autogenerated files",
    Scope = "namespaceanddescendants",
    Target = "~N:Alexandria.Persistence.Migrations"
)]
[assembly: SuppressMessage(
    "Style",
    "IDE0005:Using directive is unnecessary.",
    Justification = "<Pending>"
)]
