// <auto-generated/>
#pragma warning disable CS0618
using CleanArchitecture.WebAPI.Client.V1.Accounts;
using CleanArchitecture.WebAPI.Client.V1.Authors;
using CleanArchitecture.WebAPI.Client.V1.Books;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CleanArchitecture.WebAPI.Client.V1
{
    /// <summary>
    /// Builds and executes requests for operations under \v1
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class V1RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::CleanArchitecture.WebAPI.Client.V1.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::CleanArchitecture.WebAPI.Client.V1.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The authors property</summary>
        public global::CleanArchitecture.WebAPI.Client.V1.Authors.AuthorsRequestBuilder Authors
        {
            get => new global::CleanArchitecture.WebAPI.Client.V1.Authors.AuthorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The books property</summary>
        public global::CleanArchitecture.WebAPI.Client.V1.Books.BooksRequestBuilder Books
        {
            get => new global::CleanArchitecture.WebAPI.Client.V1.Books.BooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanArchitecture.WebAPI.Client.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CleanArchitecture.WebAPI.Client.V1.V1RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public V1RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
